name: repair
recipe: drupal8
config:
  database: mariadb
  php: '7.3'
  via: apache
#  via: nginx
  webroot: web
  xdebug: true
services:
  appserver:
    run:
      - composer install
  adminer:
    type: phpmyadmin
    hosts:
      - database

